version: '3.7'

services:
    db:
        image: postgres:12.18
        container_name: postgres_c
#        restart: always
        volumes:
            - db-volume:/var/lib/postgresql/data/
        environment:
            POSTGRES_USER: db_user:test
            POSTGRES_PASSWORD: db_password:test
            POSTGRES_DB: db_name:test
    web:
        depends_on:
            - db
        image: django_test:latest
        build:
            context: .
            dockerfile: Dockerfile
        container_name: web_c
#        restart: always
#        volumes:
#            - ./app:/var/www/html
        ports:
            - "8000:8000"

volumes:
    db-volume: