# Generated by Django 5.0.2 on 2024-03-04 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Projets')),
                ('afficher', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PageProject',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='PagesProject')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.projet')),
            ],
        ),
    ]
