# Generated by Django 5.0.2 on 2024-04-22 09:17

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageproject',
            name='sous_titre',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageproject',
            name='titre',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pageproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='projet',
            name='image',
            field=models.ImageField(upload_to=portfolio.models.get_upload_path),
        ),
    ]
