# Generated by Django 5.0.2 on 2024-03-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projet_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageproject',
            name='numero',
        ),
        migrations.AddField(
            model_name='pageproject',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageproject',
            name='ordre',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
