# Generated by Django 5.0.2 on 2024-03-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_pageproject_numero_pageproject_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='ordre',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
