# Generated by Django 5.0.2 on 2024-03-04 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projet_ordre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='afficher',
        ),
        migrations.AlterField(
            model_name='pageproject',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pages', to='portfolio.projet'),
        ),
    ]
