# Generated by Django 5.0.2 on 2024-03-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_projet_afficher_alter_pageproject_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageproject',
            name='ordre',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='projet',
            name='ordre',
            field=models.PositiveIntegerField(),
        ),
    ]
