name: Build and Deploy Docker Container

on:
  push:
    tags:
      - 'v*' # Déclencher uniquement pour les tags qui commencent par 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Django image
      run: docker build -t django_test:latest .

    - name: Tag Django image like github tag
      run: |
        TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
        docker tag django_test:latest simonmetais/django_test:$TAG

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      run: |
#        docker push simonmetais/django_test:latest
        docker push simonmetais/django_test:$TAG
